require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntryCodesController do

  # This should return the minimal set of attributes required to create a valid
  # EntryCode. As you add validations to EntryCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EntryCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all entry_codes as @entry_codes" do
      entry_code = EntryCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:entry_codes).should include(entry_code)
    end
  end

  describe "GET show" do
    it "assigns the requested entry_code as @entry_code" do
      entry_code = EntryCode.create! valid_attributes
      get :show, {:id => entry_code.to_param}, valid_session
      assigns(:entry_code).should eq(entry_code)
    end
  end

  describe "GET new" do
    it "assigns a new entry_code as @entry_code" do
      get :new, {}, valid_session
      assigns(:entry_code).should be_a_new(EntryCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested entry_code as @entry_code" do
      entry_code = EntryCode.create! valid_attributes
      get :edit, {:id => entry_code.to_param}, valid_session
      assigns(:entry_code).should eq(entry_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntryCode" do
        expect {
          post :create, {:entry_code => valid_attributes}, valid_session
        }.to change(EntryCode, :count).by(1)
      end

      it "assigns a newly created entry_code as @entry_code" do
        post :create, {:entry_code => valid_attributes}, valid_session
        assigns(:entry_code).should be_a(EntryCode)
        assigns(:entry_code).should be_persisted
      end

      it "redirects to the created entry_code" do
        post :create, {:entry_code => valid_attributes}, valid_session
        response.should redirect_to(EntryCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entry_code as @entry_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryCode.any_instance.stub(:save).and_return(false)
        post :create, {:entry_code => { "code" => "invalid value" }}, valid_session
        assigns(:entry_code).should be_a_new(EntryCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryCode.any_instance.stub(:save).and_return(false)
        post :create, {:entry_code => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entry_code" do
        entry_code = EntryCode.create! valid_attributes
        # Assuming there are no other entry_codes in the database, this
        # specifies that the EntryCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntryCode.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => entry_code.to_param, :entry_code => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested entry_code as @entry_code" do
        entry_code = EntryCode.create! valid_attributes
        put :update, {:id => entry_code.to_param, :entry_code => valid_attributes}, valid_session
        assigns(:entry_code).should eq(entry_code)
      end

      it "redirects to the entry_code" do
        entry_code = EntryCode.create! valid_attributes
        put :update, {:id => entry_code.to_param, :entry_code => valid_attributes}, valid_session
        response.should redirect_to(entry_code)
      end
    end

    describe "with invalid params" do
      it "assigns the entry_code as @entry_code" do
        entry_code = EntryCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_code.to_param, :entry_code => { "code" => "invalid value" }}, valid_session
        assigns(:entry_code).should eq(entry_code)
      end

      it "re-renders the 'edit' template" do
        entry_code = EntryCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_code.to_param, :entry_code => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entry_code" do
      entry_code = EntryCode.create! valid_attributes
      expect {
        delete :destroy, {:id => entry_code.to_param}, valid_session
      }.to change(EntryCode, :count).by(-1)
    end

    it "redirects to the entry_codes list" do
      entry_code = EntryCode.create! valid_attributes
      delete :destroy, {:id => entry_code.to_param}, valid_session
      response.should redirect_to(entry_codes_url)
    end
  end

  describe "GET guard" do
    it "asks user for entry code" do
      get :guard, {}, valid_session
    end
  end

  describe "POST guard" do
    ec1 = EntryCode.create!(:code=>"abc", :active=>true)
    ec2 = EntryCode.create!(:code=>"def", :active=>false)
    destination = "/happy/place"
    it "should redirect to final destination on valid code" do
      session[:blocked_path] = destination
      post :access, {:entry_code=>"abc"}, valid_session
      response.should redirect_to(destination)
    end
    it "should redirect to guard on nonexistant code" do
      session[:blocked_path] = destination
      post :access, {:entry_code=>"uvw"}, valid_session
      response.should redirect_to(guard_entry_codes_path)
    end
    it "should redirect to guard on non-active code" do
      session[:blocked_path] = destination
      post :access, {:entry_code=>"uvw"}, valid_session
      response.should redirect_to(guard_entry_codes_path)
    end
  end

end
